{
  "id": "CVE-2014-1624",
  "definition_id": "oval:org.debian:def:41475202633713305244541676328141464122",
  "title": "CVE-2014-1624 pyxdg",
  "description": "Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.",
  "affected": {
    "family": "unix",
    "platform": "Debian GNU/Linux 11",
    "product": "pyxdg"
  },
  "package": {
    "name": "pyxdg",
    "fixed_version": "0:0.25-4"
  },
  "references": [
    {
      "id": "CVE-2014-1624",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1624"
    }
  ]
}
