{
  "id": "CVE-2012-0215",
  "definition_id": "oval:com.ubuntu.trusty:def:201202150000000",
  "title": "CVE-2012-0215 on Ubuntu 14.04 LTS (trusty) - medium.",
  "description": "model/modelstorage.py in the Tryton application framework (trytond) before 2.4.0 for Python does not properly restrict access to the Many2Many field in the relation model, which allows remote authenticated users to modify the privileges of arbitrary users via a (1) create, (2) write, (3) delete, or (4) copy rpc call.\n\nUpdate Instructions:\n\nRun `sudo ua fix CVE-2012-0215` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\ntryton-server - 2.2.3-1\nNo subscription required",
  "note": "",
  "severity": "Medium",
  "affected": {
    "family": "unix",
    "platform": "Ubuntu 14.04 LTS"
  },
  "packages": [
    {
      "name": "tryton-server",
      "status": "not-affected",
      "note": "2.2.3-1"
    }
  ],
  "references": [
    {
      "id": "CVE-2012-0215",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-0215"
    },
    {
      "id": "",
      "source": "REF",
      "url": "https://ubuntu.com/security/CVE-2012-0215"
    },
    {
      "id": "",
      "source": "REF",
      "url": "http://news.tryton.org/2012/03/security-releases-for-all-supported.html"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "https://bugs.tryton.org/issue2476"
    }
  ],
  "public_date": "2012-07-12T20:55:00Z",
  "rights": "Copyright (C) 2012 Canonical Ltd."
}
