{
  "vulinfo_id": "JVNDB-2017-012956",
  "title": "Linux Kernel におけるエラー処理に関する脆弱性",
  "vulinfo_description": "Linux Kernel には、エラー処理に関する脆弱性が存在します。",
  "affected": [
    {
      "name": "Linux",
      "product_name": "Linux Kernel",
      "version_number": [
        "4.15.9"
      ],
      "cpe": {
        "version": "2.2",
        "text": "cpe:/o:linux:linux_kernel"
      }
    }
  ],
  "impact": {
    "cvss": [
      {
        "version": "2.0",
        "severity": {
          "type": "Base",
          "text": "Low"
        },
        "base": "2.1",
        "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
      },
      {
        "version": "3.0",
        "severity": {
          "type": "Base",
          "text": "Medium"
        },
        "base": "5.5",
        "vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      }
    ],
    "impact_item": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
  },
  "solution": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。",
  "related": [
    {
      "type": "vendor",
      "name": "GitHub",
      "vulinfo_id": "scsi: libsas: direct call probe and destruct",
      "url": "https://github.com/torvalds/linux/commit/0558f33c06bb910e2879e355192227a8e8f0219d"
    },
    {
      "type": "vendor",
      "name": "Linux Kernel",
      "vulinfo_id": "Linux Kernel Archives",
      "url": "http://www.kernel.org"
    },
    {
      "type": "vendor",
      "name": "Linux kernel source tree",
      "vulinfo_id": "scsi: libsas: direct call probe and destruct",
      "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0558f33c06bb910e2879e355192227a8e8f0219d"
    },
    {
      "type": "advisory",
      "name": "Common Vulnerabilities and Exposures (CVE)",
      "vulinfo_id": "CVE-2017-18232",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18232"
    },
    {
      "type": "advisory",
      "name": "National Vulnerability Database (NVD)",
      "vulinfo_id": "CVE-2017-18232",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-18232"
    },
    {
      "type": "cwe",
      "name": "JVNDB",
      "vulinfo_id": "CWE-388",
      "url": "https://cwe.mitre.org/data/definitions/388.html",
      "title": "エラー処理"
    }
  ],
  "history": [
    {
      "history_no": "1",
      "date_time": "2018-05-09T07:47:30Z",
      "description": "[2018年05月09日]\\n  掲載"
    }
  ],
  "date_first_published": "2018-05-09T16:47:30+09:00",
  "date_last_updated": "2018-05-09T16:47:30+09:00",
  "date_public": "2017-12-08T00:00:00+09:00"
}
