{
  "id": "CVE-2019-3871",
  "definition_id": "oval:org.opensuse.security:def:20193871",
  "title": "CVE-2019-3871",
  "description": "\n    A vulnerability was found in PowerDNS Authoritative Server before 4.0.7 and before 4.1.7. An insufficient validation of data coming from the user when building a HTTP request from a DNS query in the HTTP Connector of the Remote backend, allowing a remote user to cause a denial of service by making the server connect to an invalid endpoint, or possibly information disclosure by making the server connect to an internal endpoint and somehow extracting meaningful information about the response\n    ",
  "severity": "Important",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Leap 15.0"
    ]
  },
  "packages": [
    {
      "name": "pdns",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-geoip",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-godbc",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-ldap",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-lua",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-mydns",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-mysql",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-postgresql",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-remote",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    },
    {
      "name": "pdns-backend-sqlite3",
      "status": "released",
      "fixed_version": "0:4.1.2-lp150.3.10",
      "platform": "openSUSE Leap 15.0"
    }
  ],
  "references": [
    {
      "id": "CVE-2019-3871",
      "source": "CVE",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3871"
    },
    {
      "id": "SUSE bug 1129734",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1129734"
    }
  ]
}
