{
  "id": "CVE-2021-37690",
  "definition_id": "oval:org.opensuse.security:def:202137690",
  "title": "CVE-2021-37690",
  "description": "\n    TensorFlow is an end-to-end open source platform for machine learning. In affected versions when running shape functions, some functions (such as `MutableHashTableShape`) produce extra output information in the form of a `ShapeAndType` struct. The shapes embedded in this struct are owned by an inference context that is cleaned up almost immediately; if the upstream code attempts to access this shape information, it can trigger a segfault. `ShapeRefiner` is mitigating this for normal output shapes by cloning them (and thus putting the newly created shape under ownership of an inference context that will not die), but we were not doing the same for shapes and types. This commit fixes that by doing similar logic on output shapes and types. We have patched the issue in GitHub commit ee119d4a498979525046fba1c3dd3f13a039fbb1. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n    ",
  "severity": "Moderate",
  "impact": "moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Tumbleweed"
    ],
    "cpes": [
      "cpe:/o:opensuse:tumbleweed"
    ]
  },
  "packages": [
    {
      "name": "tensorflow-lite",
      "status": "released",
      "fixed_version": "0:2.9.1-1.1",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "tensorflow-lite-devel",
      "status": "released",
      "fixed_version": "0:2.9.1-1.1",
      "platform": "openSUSE Tumbleweed"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2021-37690",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37690"
    },
    {
      "id": "SUSE CVE-2021-37690",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2021-37690"
    },
    {
      "id": "openSUSE-SU-2022:10014-1",
      "source": "SUSE-SU",
      "url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/U25ZU2T5T4LOLSIYIMGC5PLU4PQQMJE5/"
    },
    {
      "id": "SUSE bug 1189423",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1189423"
    }
  ],
  "issued": "2022-06-30T00:00:00Z",
  "updated": "2022-06-30T00:00:00Z"
}
