{
  "id": "CVE-2022-23097",
  "definition_id": "oval:org.debian:def:264324394092531993510897435160921344859",
  "title": "CVE-2022-23097 connman",
  "description": "An issue was discovered in the DNS proxy in Connman through 1.40. forward_dns_reply mishandles a strnlen call, leading to an out-of-bounds read.",
  "affected": {
    "family": "unix",
    "platform": "Debian GNU/Linux 11",
    "product": "connman"
  },
  "package": {
    "name": "connman",
    "fixed_version": "0:0"
  },
  "references": [
    {
      "id": "CVE-2022-23097",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23097"
    }
  ]
}
