{
  "candidate": "CVE-2014-4678",
  "description": "The safe_eval function in Ansible before 1.6.4 does not properly restrict the code subset, which allows remote attackers to execute arbitrary code via crafted instructions. NOTE: this vulnerability exists because of an incomplete fix for CVE-2014-4657.",
  "ubuntu_description": "It was discovered that Ansible mishandled certain input. A remote attacker could use this to execute arbitrary code.",
  "notes": {
    "seth-arnold": "This CVE was the result of an incomplete fix for CVE-2014-4657"
  },
  "priority": "medium",
  "cvss": {
    "nvd": {
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "score": 9.8,
      "severity": "CRITICAL"
    }
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-4678",
    "https://github.com/ansible/ansible/commit/5429b85b9f6c2e640074176f36ff05fd5e4d1916"
  ],
  "public_date": "2020-02-20T03:15:00Z",
  "packages": [
    {
      "name": "ansible",
      "status": "released",
      "note": "1.6.6+dfsg-1",
      "patches": [
        {
          "source": "upstream",
          "text": "https://github.com/ansible/ansible/commit/5429b85b9f6c2e640074176f36ff05fd5e4d1916"
        }
      ]
    }
  ]
}
