{
  "id": "CVE-2018-7750",
  "elsa_id": "ELSA-2018-1124",
  "definition_id": "oval:com.oracle.elsa:def:20181124",
  "title": "\nELSA-2018-1124:  python-paramiko security update (CRITICAL)\n",
  "description": "\n[1.7.5-4]\n- Fix and enable tests (%check).\n- Backport a change which makes tests exit with nonzero status when they fail.\n- Add a fix for upstream tests for CVE-2018-7750 (broken in previous).\n\n[1.7.5-3]\n- Fix a security flaw (CVE-2018-7750) in Paramiko's server mode\n  (emphasis on **server** mode; this does **not** impact *client* use!)\n  Backported from 1.10: https://gist.github.com/stevebeattie/0eb190004e10ba0926ad8782f89676ad\n  Resolves #1557140\n",
  "severity": "CRITICAL",
  "affected": {
    "family": "unix",
    "platform": "Oracle Linux 6"
  },
  "packages": [
    {
      "name": "python-paramiko",
      "fixed_version": "0:1.7.5-4.el6_9",
      "arch": "x86_64"
    },
    {
      "name": "python-paramiko",
      "fixed_version": "0:1.7.5-4.el6_9",
      "arch": "i686"
    }
  ],
  "references": [
    {
      "id": "ELSA-2018-1124",
      "source": "elsa",
      "url": "https://linux.oracle.com/errata/ELSA-2018-1124.html"
    },
    {
      "id": "CVE-2018-7750",
      "source": "CVE",
      "url": "https://linux.oracle.com/cve/CVE-2018-7750.html"
    }
  ],
  "issued": "2018-04-12T00:00:00Z",
  "rights": "Copyright 2018 Oracle, Inc."
}
