{
  "id": "CVE-2018-11499",
  "definition_id": "oval:com.ubuntu.bionic:def:2018114990000000",
  "title": "CVE-2018-11499 on Ubuntu 18.04 LTS (bionic) - medium.",
  "description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
  "note": "",
  "severity": "Medium",
  "affected": {
    "family": "unix",
    "platform": "Ubuntu 18.04 LTS"
  },
  "packages": [
    {
      "name": "libsass",
      "status": "needed"
    }
  ],
  "references": [
    {
      "id": "CVE-2018-11499",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-11499"
    },
    {
      "id": "",
      "source": "REF",
      "url": "https://ubuntu.com/security/CVE-2018-11499"
    },
    {
      "id": "",
      "source": "REF",
      "url": "https://github.com/sass/libsass/issues/2643"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900182"
    }
  ],
  "public_date": "2018-05-26T20:29:00Z",
  "rights": "Copyright (C) 2018 Canonical Ltd."
}
