{
  "id": "CVE-2015-2317",
  "dsa_id": "DSA-3204",
  "definition_id": "oval:org.debian:def:323182963801758005689124720898202279303",
  "title": "DSA-3204-1 python-django",
  "description": "security update",
  "moreinfo": "\nDaniel Chatfield discovered that python-django, a high-level Python web development framework, incorrectly handled user-supplied redirect URLs. A remote attacker could use this flaw to perform a cross-site scripting attack.",
  "affected": {
    "family": "unix",
    "platform": "Debian GNU/Linux 7",
    "product": "python-django"
  },
  "package": {
    "name": "python-django",
    "fixed_version": "0:1.4.5-1+deb7u11"
  },
  "date": "2015-03-24T00:00:00Z",
  "references": [
    {
      "id": "CVE-2015-2317",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-2317"
    }
  ]
}
