{
  "id": "CVE-2019-8907",
  "definition_id": "oval:org.opensuse.security:def:20198907",
  "title": "CVE-2019-8907",
  "description": "\n    do_core_note in readelf.c in libmagic.a in file 5.35 allows remote attackers to cause a denial of service (stack corruption and application crash) or possibly have unspecified other impact.\n    ",
  "severity": "Moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Leap 42.3"
    ]
  },
  "packages": [
    {
      "name": "file",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "file-devel",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "file-magic",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "libmagic1",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "libmagic1-32bit",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "python-magic",
      "status": "released",
      "fixed_version": "0:5.22-16",
      "platform": "openSUSE Leap 42.3"
    }
  ],
  "references": [
    {
      "id": "CVE-2019-8907",
      "source": "CVE",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-8907"
    },
    {
      "id": "SUSE bug 1126117",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1126117"
    }
  ]
}
