{
  "vulinfo_id": "JVNDB-2016-002992",
  "title": "Symfony の SecureRandom クラスの nextBytes 関数における暗号保護メカニズムを破られる脆弱性",
  "vulinfo_description": "Symfony の SecureRandom クラスの nextBytes 関数は、paragonie/random_compat ライブラリのない PHP 5.x とともに使用される、および openssl_random_pseudo_bytes 関数が失敗する場合、乱数を適切に生成しないため、暗号保護メカニズムを破られる脆弱性が存在します。",
  "affected": [
    {
      "name": "Debian",
      "product_name": "Debian GNU/Linux",
      "version_number": [
        "8.0"
      ],
      "cpe": {
        "version": "2.2",
        "text": "cpe:/o:debian:debian_linux"
      }
    },
    {
      "name": "Sensio Labs",
      "product_name": "Symfony",
      "version_number": [
        "2.3.37 未満",
        "2.6.13 未満の 2.6.x",
        "2.7.9 未満の 2.7.x"
      ],
      "cpe": {
        "version": "2.2",
        "text": "cpe:/a:sensiolabs:symfony"
      }
    }
  ],
  "impact": {
    "cvss": [
      {
        "version": "2.0",
        "severity": {
          "type": "Base",
          "text": "Medium"
        },
        "base": "5",
        "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N"
      },
      {
        "version": "3.0",
        "severity": {
          "type": "Base",
          "text": "High"
        },
        "base": "7.5",
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
      }
    ],
    "impact_item": "攻撃者により、暗号保護メカニズムを破られる可能性があります。"
  },
  "solution": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。",
  "related": [
    {
      "type": "vendor",
      "name": "Debian Security Advisory",
      "vulinfo_id": "DSA-3588",
      "url": "https://www.debian.org/security/2016/dsa-3588"
    },
    {
      "type": "vendor",
      "name": "GitHub",
      "vulinfo_id": "do not ship with a custom rng implementation #17359",
      "url": "https://github.com/symfony/symfony/pull/17359"
    },
    {
      "type": "vendor",
      "name": "Sensio Labs",
      "vulinfo_id": "CVE-2016-1902: SecureRandom's fallback not secure when OpenSSL fails",
      "url": "http://symfony.com/blog/cve-2016-1902-securerandom-s-fallback-not-secure-when-openssl-fails"
    },
    {
      "type": "advisory",
      "name": "Common Vulnerabilities and Exposures (CVE)",
      "vulinfo_id": "CVE-2016-1902",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1902"
    },
    {
      "type": "advisory",
      "name": "National Vulnerability Database (NVD)",
      "vulinfo_id": "CVE-2016-1902",
      "url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-1902"
    },
    {
      "type": "cwe",
      "name": "JVNDB",
      "vulinfo_id": "CWE-310",
      "url": "https://jvndb.jvn.jp/ja/cwe/CWE-310.html",
      "title": "暗号の問題"
    }
  ],
  "history": [
    {
      "history_no": "0",
      "date_time": "2018-02-17T01:37:52Z",
      "description": "[2016年06月06日]\\n  掲載"
    }
  ],
  "date_first_published": "2016-06-06T16:11:37+09:00",
  "date_last_updated": "2016-06-06T16:11:37+09:00",
  "date_public": "2016-01-18T00:00:00+09:00"
}
