{
  "candidate": "CVE-2012-1502",
  "description": "Double free vulnerability in the PyPAM_conv in PAMmodule.c in PyPam 0.5.0 and earlier allows remote attackers to cause a denial of service (application crash) or possibly execute arbitrary code via a NULL byte in a password string.",
  "priority": "medium",
  "bugs": [
    "https://launchpad.net/bugs/949218"
  ],
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-1502",
    "https://ubuntu.com/security/notices/USN-1395-1"
  ],
  "assigned_to": "mdeslaur",
  "discovered_by": "Markus Vervier",
  "public_date": "2012-06-16T00:55:00Z",
  "public_date_at_usn": "2012-03-08T00:00:00Z",
  "packages": [
    {
      "name": "python-pam",
      "status": "needs-triage"
    }
  ]
}
